// Quotex OTC High-Payout Trading Assets Configuration
export interface QuotexPairDef {
  id: string;
  symbol: string;
  baseAsset: string;
  quoteAsset: string;
  name: string;
  flag: string;
  payout: number; // e.g. 93%
  basePrice: number;
  pipDecimals: number;
  volatility: 'high' | 'ultra' | 'medium';
  description: string;
}

export const QUOTEX_OTC_PAIRS: QuotexPairDef[] = [
  {
    id: 'usd_brl_otc',
    symbol: 'USD/BRL OTC',
    baseAsset: 'USD',
    quoteAsset: 'BRL',
    name: 'US Dollar / Brazilian Real (Quotex OTC)',
    flag: '🇧🇷',
    payout: 93,
    basePrice: 5.6842,
    pipDecimals: 4,
    volatility: 'ultra',
    description: 'زوج عالي الزخم والسيولة على منصة Quotex مع قنوات سعرية حادة',
  },
  {
    id: 'usd_mxn_otc',
    symbol: 'USD/MXN OTC',
    baseAsset: 'USD',
    quoteAsset: 'MXN',
    name: 'US Dollar / Mexican Peso (Quotex OTC)',
    flag: '🇲🇽',
    payout: 92,
    basePrice: 19.342,
    pipDecimals: 4,
    volatility: 'ultra',
    description: 'حركات اتجاهية قوية جداً مع ارتدادات نموذجية من مستويات الفيبوناتشي',
  },
  {
    id: 'usd_inr_otc',
    symbol: 'USD/INR OTC',
    baseAsset: 'USD',
    quoteAsset: 'INR',
    name: 'US Dollar / Indian Rupee (Quotex OTC)',
    flag: '🇮🇳',
    payout: 94,
    basePrice: 83.914,
    pipDecimals: 3,
    volatility: 'high',
    description: 'أعلى نسبة عائد على كوتكس مع احترام دقيق لكسور مناطق الدعم والمقاومة',
  },
  {
    id: 'usd_ngn_otc',
    symbol: 'USD/NGN OTC',
    baseAsset: 'USD',
    quoteAsset: 'NGN',
    name: 'US Dollar / Nigerian Naira (Quotex OTC)',
    flag: '🇳🇬',
    payout: 91,
    basePrice: 1640.5,
    pipDecimals: 2,
    volatility: 'ultra',
    description: 'تقلبات سيولة هائلة ممتازة لصفقات المومينتوم والشمعة الواحدة M1',
  },
  {
    id: 'usd_idr_otc',
    symbol: 'USD/IDR OTC',
    baseAsset: 'USD',
    quoteAsset: 'IDR',
    name: 'US Dollar / Indonesian Rupiah (Quotex OTC)',
    flag: '🇮🇩',
    payout: 92,
    basePrice: 15620.0,
    pipDecimals: 1,
    volatility: 'high',
    description: 'موجات سوينغ واضحة مع إشارات كسر كاذب سهلة الاقتناص',
  },
  {
    id: 'usd_ars_otc',
    symbol: 'USD/ARS OTC',
    baseAsset: 'USD',
    quoteAsset: 'ARS',
    name: 'US Dollar / Argentine Peso (Quotex OTC)',
    flag: '🇦🇷',
    payout: 90,
    basePrice: 980.25,
    pipDecimals: 2,
    volatility: 'ultra',
    description: 'ترندات مستمرة طويلة تعطي أفضل نسب نجاح لصفقات الاستمرار Trend Follow',
  },
  {
    id: 'eur_usd_otc',
    symbol: 'EUR/USD OTC',
    baseAsset: 'EUR',
    quoteAsset: 'USD',
    name: 'Euro / US Dollar (Quotex OTC)',
    flag: '🇪🇺',
    payout: 95,
    basePrice: 1.0845,
    pipDecimals: 5,
    volatility: 'high',
    description: 'الزوج الأكثر شعبية في كوتكس بحجم تداول مليوني يومياً',
  },
  {
    id: 'gbp_usd_otc',
    symbol: 'GBP/USD OTC',
    baseAsset: 'GBP',
    quoteAsset: 'USD',
    name: 'British Pound / US Dollar (Quotex OTC)',
    flag: '🇬🇧',
    payout: 93,
    basePrice: 1.2985,
    pipDecimals: 5,
    volatility: 'high',
    description: 'الكيبل OTC يتميز بنقاط دخول حادة وشمعات ابتلاعية واضحة',
  },
  {
    id: 'usd_egp_otc',
    symbol: 'USD/EGP OTC',
    baseAsset: 'USD',
    quoteAsset: 'EGP',
    name: 'US Dollar / Egyptian Pound (Quotex OTC)',
    flag: '🇪🇬',
    payout: 91,
    basePrice: 48.75,
    pipDecimals: 2,
    volatility: 'high',
    description: 'تحركات سعرية كلاسيكية مع ارتدادات قوية من البولنجر باند',
  },
  {
    id: 'usd_pkr_otc',
    symbol: 'USD/PKR OTC',
    baseAsset: 'USD',
    quoteAsset: 'PKR',
    name: 'US Dollar / Pakistani Rupee (Quotex OTC)',
    flag: '🇵🇰',
    payout: 92,
    basePrice: 278.4,
    pipDecimals: 2,
    volatility: 'medium',
    description: 'قنوات سعرية أفقية ممتازة لصفقات الارتداد العكسي Mean Reversion',
  },
];
